# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MiAplicacion(object):
    def setupUi(self, MiAplicacion):
        MiAplicacion.setObjectName("MiAplicacion")
        MiAplicacion.resize(493, 555)
        self.centralwidget = QtWidgets.QWidget(MiAplicacion)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 220, 231, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 30, 181, 326))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(80, 360, 151, 141))
        self.dial.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dial.setObjectName("dial")
        self.axWidget = QAxContainer.QAxWidget(self.centralwidget)
        self.axWidget.setProperty("geometry", QtCore.QRect(50, 130, 80, 70))
        self.axWidget.setObjectName("axWidget")
        MiAplicacion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MiAplicacion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MiAplicacion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MiAplicacion)
        self.statusbar.setObjectName("statusbar")
        MiAplicacion.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MiAplicacion)
        self.pushButton.clicked.connect(self.textBrowser.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MiAplicacion)
        MiAplicacion.setTabOrder(self.pushButton, self.pushButton_3)
        MiAplicacion.setTabOrder(self.pushButton_3, self.pushButton_2)
        MiAplicacion.setTabOrder(self.pushButton_2, self.pushButton_4)
        MiAplicacion.setTabOrder(self.pushButton_4, self.pushButton_6)
        MiAplicacion.setTabOrder(self.pushButton_6, self.pushButton_8)
        MiAplicacion.setTabOrder(self.pushButton_8, self.textBrowser)
        MiAplicacion.setTabOrder(self.textBrowser, self.dial)

    def retranslateUi(self, MiAplicacion):
        _translate = QtCore.QCoreApplication.translate
        MiAplicacion.setWindowTitle(_translate("MiAplicacion", "AntonioMallen"))
        self.pushButton.setText(_translate("MiAplicacion", "PushButton"))
        self.pushButton_3.setText(_translate("MiAplicacion", "PushButton"))
        self.pushButton_2.setText(_translate("MiAplicacion", "PushButton"))
        self.pushButton_4.setText(_translate("MiAplicacion", "PushButton"))
        self.pushButton_6.setText(_translate("MiAplicacion", "PushButton"))
        self.pushButton_8.setToolTip(_translate("MiAplicacion", "<html><head/><body><p>Esto es un boton</p></body></html>"))
        self.pushButton_8.setText(_translate("MiAplicacion", "PushButton"))
        self.menuMenu.setTitle(_translate("MiAplicacion", "Menu"))
from PyQt6 import QAxContainer


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiAplicacion = QtWidgets.QMainWindow()
    ui = Ui_MiAplicacion()
    ui.setupUi(MiAplicacion)
    MiAplicacion.show()
    sys.exit(app.exec())
