# Form implementation generated from reading ui file 'AntonioMallen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AntonioMallen(object):
    def setupUi(self, AntonioMallen):
        AntonioMallen.setObjectName("AntonioMallen")
        AntonioMallen.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(AntonioMallen)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 401, 361))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 80, 49, 16))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(7)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 49, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setLineWidth(5)
        self.frame_4.setMidLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(0, 70, 101, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(8)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 49, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        AntonioMallen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AntonioMallen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        AntonioMallen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AntonioMallen)
        self.statusbar.setObjectName("statusbar")
        AntonioMallen.setStatusBar(self.statusbar)

        self.retranslateUi(AntonioMallen)
        QtCore.QMetaObject.connectSlotsByName(AntonioMallen)

    def retranslateUi(self, AntonioMallen):
        _translate = QtCore.QCoreApplication.translate
        AntonioMallen.setWindowTitle(_translate("AntonioMallen", "MainWindow"))
        self.label.setText(_translate("AntonioMallen", "Antonio"))
        self.label_3.setText(_translate("AntonioMallen", "Gimeno"))
        self.label_4.setText(_translate("AntonioMallen", "2ºDAM-DUAL"))
        self.label_2.setText(_translate("AntonioMallen", "Mallen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AntonioMallen = QtWidgets.QMainWindow()
    ui = Ui_AntonioMallen()
    ui.setupUi(AntonioMallen)
    AntonioMallen.show()
    sys.exit(app.exec())
